### PR TITLE
[cjc-sweatbox] Phonebook

### PR DESCRIPTION
**Pull request by cjc-sweatbox**
See README.md for more info

## Getting Started

**IMPORTANT!** 

I have already created and staged the InitialCreate database migration in the repo.

Entity Framework will handle the database creation for you.

The console application will handle the performing of any created database migrations.

### Prerequisites

- .NET 8 SDK installed on your system.
- A code editor like Visual Studio or Visual Studio Code
- SQL Server
- SQL Server Management Studio (SSMS)

### Installation

1. Clone the repository:
    - `git clone https://github.com/cjc-sweatbox/phonebook.git`

2. Configure the application:
    - Navigate to the `.\src\Phonebook.ConsoleApp\` directory.
    - Update the `App.config` file with your database connection string.

3. Build the application:
    - `dotnet build`

### Running the Application

1. Run the application using the .NET CLI:
    - Navigate to the `.\src\Phonebook.ConsoleApp\` directory.
    - `dotnet run`

## Requirements

- [x] Application must be able to store contacts and their phone numbers.
- [x] Users must be able to perform CRUD operations against a database using a console application.
- [x] Database interaction must be via Entity Framework.
- [x] No raw SQL.
- [x] The application must contain a Contact class with at lease Id int, Name string, Email string and PhoneNumber string.
- [x] Email addresses must be validated and the expected formats communicated to the user.
- [x] Phone numbers must be validated and the expected formats communicated to the user.
- [x] The Code-First approach must be taken with Entity Framework.
- [x] The database provider must be SQL Server.

### Additional Requirements

- [x] Create categories of contacts (i.e. Family, Friends, Work, etc).

I chose not to implement the additional Email and SMS requirements due to the functionality being way out of scope for Entity Framework subject matter.

Thanks
Chris

### CODE REVIEW

**Comment by cjc-sweatbox** [comment]
Looks like the Codacy Static Code Analysis issues are with the README and using statements that are actually required.

**Review by Doc415 — CHANGES_REQUESTED** [review]
Nice project. Looks neat.
The phone number validation is only work for non numeric characters.
if i enter 2 or 2222222222222222222222222222222 it validates for phone number.
It should be better handled. You can use Regex or there are some nice libraries out there for phone validation.
Waiting for your changes.

**Comment by Doc415** [comment]
> Looks like the Codacy Static Code Analysis issues are with the README and using statements that are actually required.

Thats ok. No problem.

**Comment by cjc-sweatbox** [comment]
Thank you @Doc415.

I was using DataAnnotations to verify the input but wrongfully neglected to check for invalid inputs.

I have switched over to the [libphonenumber-csharp](https://github.com/twcclegg/libphonenumber-csharp) library which should more elegantly handle phone number validation.

**Review by Doc415 — APPROVED** [review]
Thanks for the changes. Works much better.

**Pull request closed without merging**
