### PR TITLE
Phone book project completed.

### PR DESCRIPTION
**Pull request by lawangGurung**
Thank you for assigning this console application. This project helped me learn a lot. Please be frank about the review. Again thank you for giving your precious time by reviewing my code.

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @lawangGurung - could you take a look at fixing up this exception so that I can add a contact:

image

**Comment by TheCSharpAcademy** [comment]
@lawangGurung Let us know if you need help 👌🏻

**Comment by lawangGurung** [comment]
It was just a stupid syntax error on my side. sorry for that.

**Review by lawangGurung — COMMENTED** [review]
Corrected the syntax error

**Comment by stevietv** [comment]
thanks for the tweak! I did see that it was a simple markdown syntax problem but wanted to let you solve it! Its always good to run through all functionality in your program one more time after you think its ready!

I like the setup of the project, it does what it should, and can even send Emails! I didn't test the SMS as I don't have an API key, but as that was a challenge I'd say good work on going for it!

One thing I'd say is, when viewing ALL contacts perhaps you might want to consider adding the category in the list also.

Good work, approved ✅

**Review by stevietv — APPROVED** [review]

**Pull request merged**
