### PR TITLE
Project Finished!

### PR DESCRIPTION
**Pull request by HarryjLeigh**

### CODE REVIEW

**Comment by hasona23** [comment]
Hi @HarryjLeigh  I will review your code but first of all i cant locate your project please check it is not ignored or deleted

**Comment by HarryjLeigh** [comment]
Hello @hasona23, I've figured out the issue and the files are now available  :)

**Comment by hasona23** [comment]
Hi @HarryjLeigh  how are you. Good job working on the phonebook. here some things that caught my attention
1- I Suggest that you rename user interface to App/Program or something like that because it seems that all the app logic is there you display the menu and then use the services or based on users option the program flow continues.

2- In the Press 0 or any other key to continue i suggest you add .AllowEmpty() so that if input is null or empty then you simply continue instead of having to press a key then press enter. (I know it is not much but It is something to improve user experience )

3- I suggest you make the email validation into a single regex 

4- Also I noticed that the services handles all the process for instance getting input and database communication. It is recommended that you split it into 2 to make it more modular 1-PhonebookController where you get input then pass it to services 2- PhoneBookServices that handles database communication. It just a best practice especially when exapanding or making bigger applications

5- I noticed most of you classes are static. Input,Services,Util almost everything except models and database. I suggest you dont rely heavily on using static classes because it is accessible everywhere in the program and also stays till the application closes.
6- Addional to point 5 dont make Database every function call from the service (using var context = new...()) instead make it as a private readonly variable and using dependency injection or just in the constructor of the serivce class initialise it.

7- Add the email info like host and email to configuration

8- Lastly get contact by Id should return only one contact not a list since Id is supposed to be unique .


Anyway I really liked the application and had fun reviewing it . you used spectre console well to make terminal look good and the app works fine and readme is good and tells user about changing database configuration and Smtp email and username and password.
I'll accept the submission ✅
Good Luck 🎉

**Review by ghost — COMMENTED** [review]
Approved

**Review by ghost — COMMENTED** [review]
Approved

**Review by ghost — APPROVED** [review]
Approved

**Comment by HarryjLeigh** [comment]
Hello @hasona23, thank you for the feedback! I've applied it effectively and made improvements to the code for all the points except point 6.

Could you kindly reopen the pull request to allow me to commit the updated code?

**Comment by hasona23** [comment]
Sorry for being late the request is now open to push

**Comment by hasona23** [comment]
Thanks @HarryjLeigh  for doing the project

**Pull request closed without merging**
