### PR TITLE
Working PhoneBook App

### PR DESCRIPTION
**Pull request by adityavaidya108**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@adityavaidya108 Really sorry about the delay 😟

I tried to insert a new record but I'm not passing validation and the app doesn't let me know what's the expected format.

image

**Comment by Jinboi** [comment]
Hi @adityavaidya108 ,

Hope all is well with you and that you're enjoying the C# Academy.

Just wanted to follow up on this.  Please advise if you've made any changes so that I could mark this completed. 

I'll be available. Please let me know! Thank you!

**Comment by adityavaidya108** [comment]
Hi @Jinboi I got occupied with some important work and will make the necessary changes and update the pr in some time.

**Comment by adityavaidya108** [comment]
Hey @Jinboi  can you please check now I have added the validation for expected format.

**Comment by Jinboi** [comment]
Hi @adityavaidya108 ,

Happy Sunday and hope all is well with you! 

Don't we all think our lives are just too busy now? So many things to do, so little time... :( 

On that point, thank you again for taking your precious time for your submission! Hahaha

Your project looks great and there was no problem on CRUD. 😄 

To test your project, from your original code, 

image

I've connected to my local server to test your project as below:

image

While I was testing, I ran into some errors on sending sms and emails

email error below

image

sms error below

image

I think I can mark your project as completed as you've completed all the required functions. I'll also be available for testing if you want to fix them up as well. 

Please advise what you'd like to do. Thank you! 

-Youngwoo

**Comment by TheCSharpAcademy** [comment]
@Jinboi I'm marking this one as completed as the requirements have been fulfilled 🤓

**Pull request merged**
