### PR TITLE
project finished

### PR DESCRIPTION
**Pull request by Jinboi**
Project finished

Please advise if there's any area I can improve upon.

I feel like the validation on email and phoneNumber could be better.

Will revisit in the future to improve upon them.

As always, thank you for your guidance. Have a good day! 

-Bata13

### CODE REVIEW

**Review by VocalNight — CHANGES_REQUESTED** [review]
Hey. Good job on the project! I specially liked how you did the menu interface and how you organized your input method.

There's a few things that i noticed.

* If i choose the option "View Contact" when there are no contacts registered in the DB, i get an exception. It would be desirable instead to simply show a message saying "no data".

image

* When updating a contact. the name changes, but the email and the phone number remain the same. 

* Your email filtering could be better, right now it accepts strings like "@@@@@"
Take a look into Regex and how you can use it with C#. 
If you haven't heard of regex, take a look in this site, i find it to be the best introduction to regex: https://www.regexone.com/

**Comment by Jinboi** [comment]
Hi VocalNight,

Thank you very much for your comments!! Really appreciate it.

I've made code changes as you've requested.
- If there's no contact to update, there'll be a message saying no contact to update
- I've fixed the issue of bug so it'd show updated email and phone number correctly
- I've used regex for email and phone number validation

With these changes updated, I've made a new commit by pushing to the main branch on Jinboi/CodeReviews.Console.Phonebook.

Please let me know if there's any issues! 
Once again, thank you very much for your guidance!! 

Have a good weekend! Hahaha
-Bata13

**Comment by VocalNight** [comment]
Could you double check your commit? It seems all files in the pull request got deleted.

image

**Comment by Jinboi** [comment]
Hi VocalNight,

I've re-commited after fixing the issue. 

The confusion happened because I've deleted all the files and added a folder called STUDY.PhoneBook with updated files. 

It should be good now. Please let me know. 

image

**Comment by VocalNight** [comment]
Everything looks pretty good now!
Good job on the regex, it's a nice skill to have, so make sure to keep playing with it every now and then.

I will be approving the project, good luck on your next ones!

**Review by VocalNight — APPROVED** [review]
Everything looks pretty good now!
Good job on the regex, it's a nice skill to have, so make sure to keep playing with it every now and then.

I will be approving the project, good luck on your next ones!

**Pull request closed without merging**
