### PR TITLE
Finished app

### PR DESCRIPTION
**Pull request by furiax**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@furiax well done! The project is looking good! 

However I find a bug: 
image

The user shouldn't be allowed to create a user if there's no category, otherwise this menu will break. Let me know if you have questions.

**Comment by furiax** [comment]
Ok seems like I forgot to test my program with an empty database 😊 😊 
It seems all my other methods had the same problem as well so I added if loops to check if the lists are empty. If they are empty a message is displayed and the methods aren't executed.

I also noticed my update contact method didn't contain the possibilty to change categories so I added that also 😉

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@furiax Found another bug! 
image. It's good that you don't allow duplicate names but you gotta handle that scenario. I don't recommend you use error handling for this, but instead handle it in code since it's an expected error.

**Comment by furiax** [comment]
Added validation for it now 😉

**Pull request merged**
