### PR TITLE
done

### PR DESCRIPTION
**Pull request by kwm0304**

### CODE REVIEW

**Comment by kwm0304** [comment]
Twilio rejected my toll free request, so sms will not work

**Comment by stevietv** [comment]
Hi @kwm0304 - thanks for the submission.
Can you please fix the handling of this error, currently I can't run it:

```
Unhandled exception. System.InvalidOperationException: TWILIO_SID environment variable is not set.
   at Phonebook.kwm0304.Utils.SmsHandler..ctor() in E:\Development\study\CSharpAcademy\CodeReviews.Console.Phonebook\Phonebook.kwm0304\Utils\SMSHandler.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Phonebook.kwm0304.Program.Main(String[] args) in E:\Development\study\CSharpAcademy\CodeReviews.Console.Phonebook\Phonebook.kwm0304\Program.cs:line 24
   at Phonebook.kwm0304.Program.<Main>(String[] args)
```

**Comment by kwm0304** [comment]
@stevietv should be good now

**Comment by kwm0304** [comment]
@stevietv should be good now

**Comment by stevietv** [comment]
Hey, thanks for making the changes as we discussed. I've now been able to test your program and came across a few small issues:

* Viewing contacts when there are none causes a null-reference exception - It would be good to handle this
* I'm unable to edit a contacts email address
*  You haven't stated what format the phone number should be in - I wasn't able to use my own number (format `0612345678` or `31612345678`) - you'd need to update the input prompt.

Only the last bullet point is a  REQUIREMENT to pass the project, the others would be nice to haves.

Nce job tackling the mail service also. I'd recommend in future not hardcoding 4 servers into the code, but allowing users to add their own server details in the appsettings.json - I wasn't able to use my own mail server to test this.

all round, great attempt! few small tweaks and its there! 💪🏻

**Comment by stevietv** [comment]
Thanks for working on this, you got there! Approved! ✅ 

One tip for something in the future, there are lots of libraries out there that you can use to validate phonenumbers, for example https://www.nuget.org/packages/PhoneNumberParser

**Review by stevietv — APPROVED** [review]

**Pull request merged**
