### PR TITLE
Finished Project

### PR DESCRIPTION
**Pull request by MansoorAZafar**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey i cannot add migration or update database. When i try , i get this errors:
image


Can you give directions how to setup and run your application in the readme file please

And i also get this exception when i try to run the app:
image

**Comment by TheCSharpAcademy** [comment]
@MansoorAZafar Let us know if you need help 😁

**Review by Doc415 — CHANGES_REQUESTED** [review]
Thanks for the fix.
image
There should be an e-mail validator 

image

image

Model directory should only include model types
You can create a new data directiory for database classes and you can move menu selections to UI directory
It is better to have organised structure.
Waiting for your updates.

**Review by Doc415 — APPROVED** [review]
Good job

**Pull request closed without merging**
