### PR TITLE
submitting for review

### PR DESCRIPTION
**Pull request by frockett**

### CODE REVIEW

**Comment by frockett** [comment]
I'm leaving the name of the DTO class unchanged since DTO is more readable as an initialism

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@frockett Thanks for submitting! It looks like updating isn't working correctly. I can update the phone number but not the e-mail or names. 

Also, optionally, It would also be a good challenge to require an user to be part of a category, even if there's a default category in case none was added.

**Comment by frockett** [comment]
Fixed the issue with updating the contact, it was problem with the update logic in the repository

**Comment by frockett** [comment]
Also maybe I'm misunderstanding your suggestion for the challenge. Currently, groups can be created from within the group submenu and a contact can be added to a group by selecting the contact in the contact menu. The user has to create a group first. Then, the user can select the contact, select "Add/Remove from group" and, choose the group to which they want to add the contact. Otherwise, if the contact is already in a group, then the user will be prompted to confirm that they want to remove the contact from that group. 

If the user deletes a group, they will be prompted to decide whether to delete all associated contacts. If they choose no, it will just return the contacts to their default, non-categorized.

I have it set up so that there is no default group, and contacts can either be in one group at a time or no group at all. Would having them all be in a default group upon creation be better?

**Comment by TheCSharpAcademy** [comment]
@frockett This is a personal choice but I'd create a "non-categorized" category to enforce relational data. Up to you really. 😁

**Pull request merged**
