### PR TITLE
Phone Book App project finished

### PR DESCRIPTION
**Pull request by LucianoNicolasArrieta**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@LucianoNicolasArrieta At the moment I can't add contacts. Could you please check?

image

**Comment by LucianoNicolasArrieta** [comment]
Sorry if i made it a little bit confusing haha :sweat_smile:, but you first have to select a category in order to add a contact

**Comment by TheCSharpAcademy** [comment]
@LucianoNicolasArrieta That makes more sense. I'll approve the project, but just for reference, ideally you'd like to remove the "Category" column from the contact since it's redundant (especially when just passing the enum and not the name of the category). You code use a DTO for that. 

image

**Comment by TheCSharpAcademy** [comment]
@LucianoNicolasArrieta Also whenever dealing with phone numbers, make sure you add validation (you can use regex), so this isn't allowed: 
image

**Pull request merged**
