### PR TITLE
Phonebook console app

### PR DESCRIPTION
**Pull request by ananttuli**
(Note: 1 codacy README issue)

### Requirements (all completed)
- [x] This is an application where you should record contacts with their phone numbers.
- [x] Users should be able to Add, Delete, Update and Read from a database, using the console.
 You need to use Entity Framework, raw SQL isn't allowed.
 Your code should contain a base Contact class with AT LEAST {Id INT, Name STRING, Email STRING and Phone Number(STRING)}
- [x] You should validate e-mails and phone numbers and let the user know what formats are expected
- [x] You should use Code-First Approach, which means EF will create the database schema for you.
- [x] You should use SQL Server, not SQLite

### Challenges (1/3)

- [ ] Create a functionality that allows users to add the contact's e-mail address and send an e-mail message from the app.
- [x] Expand the app by creating categories of contacts (i.e. Family, Friends, Work, etc).
- [ ] What if you want to send not only e-mails but SMS?

### CODE REVIEW

**Comment by ananttuli** [comment]
@Jinboi Thanks for the feedback. Should this PR be closed or merged ?

**Comment by Jinboi** [comment]
@TheCSharpAcademy , @ananttuli 
It should be merged.

**Comment by ananttuli** [comment]
@Jinboi The PR will need to be approved in order to be merged 🙏 

image

**Review by Jinboi — APPROVED** [review]
Approving this as everything is good

**Comment by Jinboi** [comment]
Hi @ananttuli ,

I have approved this on Github so you should be able to merge soon. Thank you!

**Pull request closed without merging**
