### PR TITLE
Completed PhoneBook app

### PR DESCRIPTION
**Pull request by N-Endy**
I tried implementing the email service but I keep getting a service error. The code is still attached so I can work on it at a later date.

Other functionalities function as intended

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
when i try to update the email of contact, it does not validate new input
image

E-mail function is working well with my google app pass.

**Review by Doc415 — CHANGES_REQUESTED** [review]
when i am updateing contact email, it does not validate new input
image

e mail function is working, there is no problem.

**Comment by N-Endy** [comment]
I'll fix that now. Thank you

**Comment by N-Endy** [comment]
Validation has been added to the UpdateContact for both email and phone
number

**Review by Doc415 — APPROVED** [review]
Nice work. Ready for next project :)

**Pull request closed without merging**
