### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by Deviationlark**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
When i enter nonvalid phone number , app crashes ---> necessary
image

Suggestions:    ---->not necessary

**it would be nice to have an option to retrun previous menu in each menu
** user prompt and confirmation for deleting record would be nice

**i should be able to select recepient phone number from records
image

**Review by Doc415 — CHANGES_REQUESTED** [review]
when i enter a valid phone number , after entering category , app says the phone number invalid and asks for phone number and enters a loop

image

**Comment by Deviationlark** [comment]
i commend you for finding that bug, confused me how you did it at first but i think i fixed it because i couldn't replicate it anymore

**Review by Doc415 — CHANGES_REQUESTED** [review]
Ok that one seems to be fixed.
When there are two contacts with same name, and i try to delete one of them app throws exception. You should not get the contact with name(because there can be many contacts with same name), instead you should use id to get the contact . 
image

**Review by Doc415 — CHANGES_REQUESTED** [review]
When i try to update a contact, if there are other contacts with same name, app asks to choose from ids. When i select an id, it keep asking id in loop
Here is how it looks

https://github.com/TheCSharpAcademy/CodeReviews.Console.Phonebook/assets/94632226/67d3490c-5a13-442d-bcf1-54d1650458c1

**Review by Doc415 — APPROVED** [review]

**Pull request closed without merging**
